# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

development:
  url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com

production:
  url: "https://azure-chasm.cloudvent.net" # the base hostname & protocol for your site, e.g. http://example.com

title: Golden Robot Records
email: info@goldenrobotrecords.com
description: > # this means to ignore newlines until "baseurl:"
  Golden Robot Records is a powerhouse independent Worldwide record label who embrace, develop and finance their hand picked artists giving each band the support they need to get their music released across the globe.
baseurl: "" # the subpath of your site, e.g. /blog
spotify_username: https://open.spotify.com/user/goldenrobotrecords/playlist/3Ge2LlIDcSr1GjWIrKFZP7?si=EjFoMSKqTeCoAzHIpqHHSg
facebook_username: https://www.facebook.com/goldenrobotrecords/
instagram_username: https://www.instagram.com/goldenrobotrecords/
twitter_username: https://twitter.com/goldenrobotrec
youtube_username: https://www.youtube.com/channel/UCJyJOTeFHqnAmMDf7RxSKkQ

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
permalink: pretty

collections:
  golden-robot-records:
    output: true
  x-ray-records:
    output: true
  riot-records:
    output: true
  social-family-records:
    output: true
  catalogue:
    output: false

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
