# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Golden Robot Records
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://azure-chasm.cloudvent.net" # the base hostname & protocol for your site, e.g. http://example.com
spotify_username: https://twitter.com/goldenrobotrec
twitter_username: https://twitter.com/goldenrobotrec
youtube_username: https://www.facebook.com/goldenrobotrecords
facebook_username: https://www.facebook.com/goldenrobotrecords
instagram_username: https://www.instagram.com/goldenrobotrecs

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
permalink: pretty

collections:
  golden-robot-records:
    output: true
  x-ray-records:
    output: true
  riot-records:
    output: true

defaults:
  - scope:
      type: golden-robot-records
      path: "/golden-robot-records/"
    values:
      layout: artist
      image: 'http://lorempixel.com/800/800'
      name: 'Artist Name'
      order: 100
      hidden: false
      hero: http://lorempixel.com/1800/660
      twitter: https://google.com
      facebook: https://google.com
      instagram: https://google.com
      spotify: https://google.com
      apple: https://google.com
      youtube: https://google.com
      albumns: 
        - image_path: http://lorempixel.com/801/801
        - image_path: http://lorempixel.com/802/802
        - image_path: http://lorempixel.com/803/803
        - image_path: http://lorempixel.com/804/804
  - scope:
      type: x-ray-records
      path: "/x-ray-records/"
    values:
      layout: artist
      image: 'http://lorempixel.com/800/800'
      name: 'Artist Name'
      order: 100
      hidden: false
      hero: http://lorempixel.com/1800/660
      twitter: https://google.com
      facebook: https://google.com
      instagram: https://google.com
      spotify: https://google.com
      apple: https://google.com
      youtube: https://google.com
      albumns: 
        - image_path: http://lorempixel.com/801/801
        - image_path: http://lorempixel.com/802/802
        - image_path: http://lorempixel.com/803/803
        - image_path: http://lorempixel.com/804/804
  - scope:
      type: riot-records
      path: "/riot-records/"
    values:
      layout: artist
      image: 'http://lorempixel.com/800/800'
      name: 'Artist Name'
      order: 100
      hidden: false
      hero: http://lorempixel.com/1800/660
      twitter: https://google.com
      facebook: https://google.com
      instagram: https://google.com
      spotify: https://google.com
      apple: https://google.com
      youtube: https://google.com
      albumns: 
        - image_path: http://lorempixel.com/801/801
        - image_path: http://lorempixel.com/802/802
        - image_path: http://lorempixel.com/803/803
        - image_path: http://lorempixel.com/804/804

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
